; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ttgo-t1]
platform = espressif32
board = ttgo-t1
framework = arduino
lib_extra_dirs = C:/Users/Joosep/Documents/Arduino/libraries
monitor_speed = 115200
build_flags =
    -std=gnu++11
    -DCORE_DEBUG_LEVEL=5
lib_deps =
    fastled/FastLED@^3.5.0

; Include specific files and exclude duplicates to fix link errors
build_src_filter =
    +<*>
    -<main.ino>
    +<core/>
    -<MainController.cpp>
    -<MainController.h>
